name: sat_prep_app
description: "A customized SAT preparation learning system."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  firebase_core: 4.11.0
  firebase_auth: 6.5.2
  google_sign_in: 7.2.0

  flutter_native_splash: ^2.4.8
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/logo.png
    - assets/translations/