// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtntDC5FYU71DRwhE2j7sNCcP8mq_7zE',
    appId: '1:750793925254:web:32745c84585e61ae8e6707',
    messagingSenderId: '750793925254',
    projectId: 'sat-prep-app-e2837',
    authDomain: 'sat-prep-app-e2837.firebaseapp.com',
    storageBucket: 'sat-prep-app-e2837.firebasestorage.app',
    measurementId: 'G-Z7NX4ZBFFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzEssNQKin_tBlqUnC3fAJfHCA4Wy0t9Q',
    appId: '1:750793925254:android:2fdd10001d6778d78e6707',
    messagingSenderId: '750793925254',
    projectId: 'sat-prep-app-e2837',
    storageBucket: 'sat-prep-app-e2837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTuW6Gno9zg9LKVv_Gsh9MU5Ti0S-hZZo',
    appId: '1:750793925254:ios:7b13f471089eec3b8e6707',
    messagingSenderId: '750793925254',
    projectId: 'sat-prep-app-e2837',
    storageBucket: 'sat-prep-app-e2837.firebasestorage.app',
    iosBundleId: 'com.example.satPrepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTuW6Gno9zg9LKVv_Gsh9MU5Ti0S-hZZo',
    appId: '1:750793925254:ios:7b13f471089eec3b8e6707',
    messagingSenderId: '750793925254',
    projectId: 'sat-prep-app-e2837',
    storageBucket: 'sat-prep-app-e2837.firebasestorage.app',
    iosBundleId: 'com.example.satPrepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQtntDC5FYU71DRwhE2j7sNCcP8mq_7zE',
    appId: '1:750793925254:web:f165c91f8d8800ae8e6707',
    messagingSenderId: '750793925254',
    projectId: 'sat-prep-app-e2837',
    authDomain: 'sat-prep-app-e2837.firebaseapp.com',
    storageBucket: 'sat-prep-app-e2837.firebasestorage.app',
    measurementId: 'G-D2TLV9G5Q6',
  );
}
